version: '3.8'

services:
  postgres:
    image:
      postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./.docker/postgres/iam:/var/lib/postgresql/data