version: '3.8'

services:
  postgres:
    image:
      postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./base_dev_db.sql:/docker-entrypoint-initdb.d/base_dev_db.sql
      - ./.docker/postgres/iam:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
    ports:
      - "127.0.0.1:30001:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-dev
    ports:
      - "127.0.0.1:30000:80"